#!/bin/bash
# Module: Shell Setup
# Description: Configure shell with custom aliases, functions, and settings
# Dependencies: common.sh

# Main shell setup function
setup_custom_shell() {
    echo ""

    # Run setup functions with error checking
    if ! setup_bash_aliases; then
        track_failure "Shell Configuration" "Alias kurulumu başarısız"
        return 1
    fi

    if ! setup_custom_functions; then
        track_failure "Shell Configuration" "Fonksiyon kurulumu başarısız"
        return 1
    fi

    if ! setup_bashrc_enhancements; then
        track_failure "Shell Configuration" "Bashrc geliştirmeleri başarısız"
        return 1
    fi

    if ! setup_starship_config; then
        track_failure "Shell Configuration" "Starship config başarısız"
        return 1
    fi

    track_success "Shell Configuration" "(62 aliases, starship, enhancements)"
    echo -e "\n${GREEN}[BAŞARILI]${NC} Shell ortamı yapılandırması tamamlandı!"
    echo -e "${YELLOW}[BİLGİ]${NC} Değişikliklerin aktif olması için: ${GREEN}source ~/.bashrc${NC}"
    return 0
}

# Setup custom aliases
setup_bash_aliases() {
    echo -e "${YELLOW}[BİLGİ]${NC} Özel alias'lar yapılandırılıyor..."

    local ALIASES_FILE="$HOME/.bash_aliases"

    # Create backup if file exists
    if [ -f "$ALIASES_FILE" ]; then
        cp "$ALIASES_FILE" "${ALIASES_FILE}.backup.$(date +%Y%m%d_%H%M%S)"
        echo -e "${CYAN}[BİLGİ]${NC} Mevcut .bash_aliases yedeklendi."
    fi

    # Write aliases to file
    cat > "$ALIASES_FILE" << 'EOF'
# ============================================================================
# Custom Aliases - Auto-generated by 1453 WSL Setup
# ============================================================================

# Project navigation shortcuts
alias home='cd ~'
alias projects='cd ~/projects'
alias dl='cd ~/Downloads'

# Clear screen aliases
alias c='clear'
alias cl='clear'
alias cls='clear'

# Modern tool replacements (conditionally loaded if installed)
# bat/batcat - better cat
if command -v batcat &>/dev/null; then
    alias cat='batcat'
elif command -v bat &>/dev/null; then
    alias cat='bat'
fi

# ripgrep - better grep
if command -v rg &>/dev/null; then
    alias grep='rg'
fi

# fd - better find
if command -v fdfind &>/dev/null; then
    alias find='fdfind'
elif command -v fd &>/dev/null; then
    alias find='fd'
fi

# eza - better ls
if command -v eza &>/dev/null; then
    alias ls='eza --icons --group-directories-first'
    alias ll='eza --icons --group-directories-first -l -g --git'
    alias la='eza -a --icons --group-directories-first'
    alias lt='eza --icons --group-directories-first --tree --level=2'
    alias llt='eza --icons --group-directories-first -l -g --git --tree --level=2'
    alias lh='eza -d .* --icons'
else
    alias ll='ls -lh'
    alias la='ls -lAh'
    alias lt='ls -lhR'
    alias lh='ls -ldh .*'
fi

# Tree command (install if available)
if command -v tree &>/dev/null; then
    alias tree='tree -C -L 2 --dirsfirst'
fi

# Navigation shortcuts
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias back='cd -'
alias up='cd ..'
alias up2='cd ../..'
alias up3='cd ../../..'

# Directory creation and navigation
alias mkcd='mcd'  # Uses the mcd function defined in bashrc

# lazydocker - Docker TUI
if command -v lazydocker &>/dev/null; then
    alias ld='lazydocker'
else
    alias ld='docker ps -a'
fi

# lazygit - Git TUI
if command -v lazygit &>/dev/null; then
    alias lg='lazygit'
else
    alias lg='git log --oneline --graph --decorate --all'
fi

# Safe operations
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'

# System information
alias cpuinfo='lscpu'
alias meminfo='free -m -l -t'
alias disk='df -h'
alias ports='netstat -tulanp'
alias myip="curl -s http://whatismijnip.nl | cut -d ' ' -f 5"

# Git aliases
alias g='git'
alias ga='git add'
alias gaa='git add --all'
alias gb='git branch'
alias gc='git commit -m'
alias gca='git commit --amend'
alias gco='git checkout'
alias gl='git log --oneline --graph --decorate'
alias gp='git push'
alias gpf='git push --force-with-lease'
alias gpl='git pull'
alias gs='git status -s'
alias gst='git status'

# Docker aliases
alias dps='docker ps'
alias dpsa='docker ps -a'
alias di='docker images'
alias dex='docker exec -it'
alias dlog='docker logs -f'
alias dstop='docker stop $(docker ps -q)'
alias drm='docker rm $(docker ps -aq)'
alias dclean='docker system prune -af'

# NPM aliases
alias ni='npm install'
alias nid='npm install --save-dev'
alias nig='npm install -g'
alias nci='rm -rf node_modules package-lock.json && npm install'
alias ns='npm start'
alias nd='npm run dev'
alias nb='npm run build'
alias nt='npm test'

# Python aliases
alias py='python3'
alias pip='pip3'
alias venv='python3 -m venv'
alias activate='source venv/bin/activate'

# Process management
alias pg='ps aux | grep'

# Shell config editing
alias bashrc='nano ~/.bashrc'
alias aliases='nano ~/.bash_aliases'
alias reload='source ~/.bashrc'

# Note: Zoxide 'z' command is automatically available if zoxide is installed
# It's initialized via 'eval "$(zoxide init bash)"' in bashrc enhancements

EOF

    # Ensure .bashrc sources .bash_aliases
    if ! grep -q "\.bash_aliases" "$HOME/.bashrc" 2>/dev/null; then
        echo "" >> "$HOME/.bashrc"
        echo "# Source custom aliases" >> "$HOME/.bashrc"
        echo "[ -f ~/.bash_aliases ] && . ~/.bash_aliases" >> "$HOME/.bashrc"
    fi

    echo -e "${GREEN}[BAŞARILI]${NC} Alias'lar yapılandırıldı: $ALIASES_FILE"
    return 0
}

# Setup custom functions
setup_custom_functions() {
    echo -e "${YELLOW}[BİLGİ]${NC} Özel fonksiyonlar ekleniyor..."

    local BASHRC="$HOME/.bashrc"

    # FIX: Idempotent install - Remove old block if exists, then add fresh one
    # This prevents duplicate blocks from repeated installations
    if grep -q "$BASHRC_MARKER_FUNCTIONS_START" "$BASHRC" 2>/dev/null; then
        echo -e "${CYAN}[!]${NC} Mevcut özel fonksiyonlar bulundu, güncelleniyor..."
        # Remove old block completely (from START marker to END marker)
        sed -i "/$BASHRC_MARKER_FUNCTIONS_START/,/$BASHRC_MARKER_FUNCTIONS_END/d" "$BASHRC"
    fi

    # Add custom functions to .bashrc
    # FIX: Use marker variables from constants.sh instead of hardcoded strings
    cat >> "$BASHRC" << 'EOF'

# $BASHRC_MARKER_FUNCTIONS_START
# Create directory and cd into it
# FIX BUG-008: Use 'return' instead of 'exit' to avoid killing the shell
mcd() {
    mkdir -p "\$1" && cd "\$1" || return 1
}

# Make file executable
# FIX BUG-007: Renamed from 'make()' to 'mkexec()' to avoid shadowing system 'make' command
mkexec() {
    chmod +x "\$1"
}

# GitHub: Create new project and push to GitHub
# Usage: ghnew <project-name> [--private] [--public]
ghnew() {
    local project_name="\$1"
    local visibility="public"
    
    # Check if gh is installed
    if ! command -v gh &>/dev/null; then
        echo "❌ GitHub CLI (gh) kurulu değil!"
        echo "Kurulum için: gh auth login"
        return 1
    fi
    
    # Check if authenticated
    if ! gh auth status &>/dev/null; then
        echo "❌ GitHub'a giriş yapılmamış!"
        echo "Önce giriş yapın: gh auth login"
        return 1
    fi
    
    # Validate project name
    if [ -z "\$project_name" ]; then
        echo "❌ Proje adı gerekli!"
        echo "Kullanım: ghnew <proje-adı> [--private|--public]"
        return 1
    fi
    
    # Check for visibility flag
    if [[ "\$2" == "--private" ]]; then
        visibility="private"
    elif [[ "\$2" == "--public" ]]; then
        visibility="public"
    fi
    
    # Check if directory already exists
    if [ -d "\$project_name" ]; then
        echo "⚠️  Klasör zaten mevcut: \$project_name"
        echo "Devam etmek istiyor musunuz? (y/N)"
        read -r response
        if [[ ! "\$response" =~ ^[yY]\$ ]]; then
            echo "İptal edildi."
            return 1
        fi
        cd "\$project_name" || return 1
    else
        # Create project directory
        mkdir -p "\$project_name" || {
            echo "❌ Klasör oluşturulamadı!"
            return 1
        }
        cd "\$project_name" || return 1
    fi
    
    echo "📁 Proje klasörü: \$(pwd)"
    
    # Initialize git if not already initialized
    if [ ! -d .git ]; then
        echo "🔧 Git başlatılıyor..."
        git init || {
            echo "❌ Git init başarısız!"
            return 1
        }
    fi
    
    # Create README if doesn't exist
    if [ ! -f README.md ]; then
        echo "📝 README.md oluşturuluyor..."
        cat > README.md << READMEEOF
# \$project_name

## Açıklama
Bu proje otomatik olarak oluşturuldu.

## Kurulum
\\\`\\\`\\\`bash
# Kurulum adımları buraya
\\\`\\\`\\\`

## Kullanım
\\\`\\\`\\\`bash
# Kullanım örnekleri buraya
\\\`\\\`\\\`

## Lisans
MIT
READMEEOF
    fi
    
    # Create .gitignore if doesn't exist
    if [ ! -f .gitignore ]; then
        echo "🚫 .gitignore oluşturuluyor..."
        cat > .gitignore << GITIGNOREEOF
# Dependencies
node_modules/
venv/
__pycache__/
*.pyc

# Build outputs
dist/
build/
*.log

# IDE
.vscode/
.idea/
*.swp

# OS
.DS_Store
Thumbs.db

# Environment
.env
.env.local
GITIGNOREEOF
    fi
    
    # Add and commit
    echo "💾 İlk commit yapılıyor..."
    git add . || {
        echo "❌ Git add başarısız!"
        return 1
    }
    
    git commit -m "Initial commit: Setup \$project_name" || {
        echo "❌ Git commit başarısız!"
        return 1
    }
    
    # Create GitHub repo
    echo "🌐 GitHub'da repo oluşturuluyor (\$visibility)..."
    if [ "\$visibility" = "private" ]; then
        gh repo create "\$project_name" --private --source=. --push || {
            echo "❌ GitHub repo oluşturma başarısız!"
            return 1
        }
    else
        gh repo create "\$project_name" --public --source=. --push || {
            echo "❌ GitHub repo oluşturma başarısız!"
            return 1
        }
    fi
    
    echo ""
    echo "✅ Proje başarıyla oluşturuldu ve GitHub'a gönderildi!"
    echo "📦 Repo: https://github.com/\$(gh api user --jq '.login')/\$project_name"
    echo "📁 Yerel: \$(pwd)"
}

# GitHub: Quick commit and push
# Usage: ghpush "commit message"
ghpush() {
    local commit_msg="\${1:-"Quick update"}"
    
    # Check if we're in a git repo
    if [ ! -d .git ]; then
        echo "❌ Bu bir git repository değil!"
        return 1
    fi
    
    echo "💾 Değişiklikler commit ediliyor..."
    git add .
    git commit -m "\$commit_msg" || {
        echo "⚠️  Commit başarısız (değişiklik yok olabilir)"
        return 1
    }
    
    echo "📤 GitHub'a gönderiliyor..."
    git push || {
        echo "❌ Push başarısız!"
        return 1
    }
    
    echo "✅ Başarıyla gönderildi!"
}

# GitHub: Quick clone with cd
# Usage: ghclone <repo-url-or-username/repo>
ghclone() {
    if [ -z "\$1" ]; then
        echo "❌ Repo adresi gerekli!"
        echo "Kullanım: ghclone <username/repo> veya ghclone <url>"
        return 1
    fi
    
    gh repo clone "\$1" || {
        echo "❌ Clone başarısız!"
        return 1
    }
    
    # Extract repo name and cd into it
    local repo_name
    repo_name=\$(basename "\$1" .git)
    if [ -d "\$repo_name" ]; then
        cd "\$repo_name" || return 1
        echo "✅ Clone başarılı! Dizin: \$(pwd)"
    fi
}
# $BASHRC_MARKER_FUNCTIONS_END

EOF

    echo -e "${GREEN}[BAŞARILI]${NC} Özel fonksiyonlar eklendi."
    return 0
}

# Setup enhanced bashrc configuration
setup_bashrc_enhancements() {
    echo -e "${YELLOW}[BİLGİ]${NC} Bash yapılandırması geliştiriliyor..."

    local BASHRC="$HOME/.bashrc"

    # FIX: Idempotent install - Remove old block if exists, then add fresh one
    # This prevents duplicate blocks from repeated installations
    if grep -q "$BASHRC_MARKER_CONFIG_START" "$BASHRC" 2>/dev/null; then
        echo -e "${CYAN}[!]${NC} Mevcut Bash yapılandırması bulundu, güncelleniyor..."
        # Remove old block completely (from START marker to END marker)
        sed -i "/$BASHRC_MARKER_CONFIG_START/,/$BASHRC_MARKER_CONFIG_END/d" "$BASHRC"
    fi

    # Add enhanced configuration
    # FIX: Use marker variables from constants.sh instead of hardcoded strings
    cat >> "$BASHRC" << EOF

# $BASHRC_MARKER_CONFIG_START

# History settings
export HISTCONTROL=ignoreboth:erasedups
export HISTSIZE=100000
export HISTFILESIZE=200000
export HISTTIMEFORMAT="%F %T "
export HISTIGNORE="ls:ll:la:pwd:exit:history:clear:cd"
shopt -s histappend

# Update history after each command
PROMPT_COMMAND="history -a; history -c; history -r; \${PROMPT_COMMAND:-}"

# Terminal settings
export TERM=xterm-256color

# Modern tool configurations
# NOTE: eval usage here is SAFE (official pattern from tool documentation)
# - starship/zoxide init: trusted binary, hardcoded command, no user input
# - Different from package installation eval (which had command injection risk)
# - Official recommended method: https://starship.rs/guide/
if command -v starship &>/dev/null; then
    # Clear command hash to ensure we use the correct binary location
    # This prevents errors if starship was moved/reinstalled (e.g. /usr/local/bin -> /usr/bin)
    hash -r 2>/dev/null
    eval "\$(starship init bash)"
fi

if command -v zoxide &>/dev/null; then
    eval "\$(zoxide init bash)"
fi

if command -v vivid &>/dev/null; then
    export LS_COLORS="\$(vivid generate catppuccin-mocha)"
fi

# FZF configuration
if [ -f /usr/share/doc/fzf/examples/key-bindings.bash ]; then
    source /usr/share/doc/fzf/examples/key-bindings.bash
fi

if [ -f /usr/share/doc/fzf/examples/completion.bash ]; then
    source /usr/share/doc/fzf/examples/completion.bash
fi

# FZF default options (modern theme)
if command -v fzf &> /dev/null; then
    export FZF_DEFAULT_OPTS='--color=bg+:#313244,bg:#1e1e2e,spinner:#f5e0dc,hl:#f38ba8 --color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc --color=marker:#f5e0dc,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8 --border=rounded --height=80% --layout=reverse'
fi

# Add ~/.local/bin to PATH
export PATH="\$HOME/.local/bin:\$PATH"

# WSL specific settings
export BROWSER=wslview

# $BASHRC_MARKER_CONFIG_END

EOF

    echo -e "${GREEN}[BAŞARILI]${NC} Bash yapılandırması geliştirildi."
    return 0
}

# Setup Starship configuration
setup_starship_config() {
    if ! command -v starship &> /dev/null; then
        echo -e "${CYAN}[BİLGİ]${NC} Starship kurulu değil, config atlanıyor."
        return 0
    fi

    echo -e "${YELLOW}[BİLGİ]${NC} Starship yapılandırması oluşturuluyor..."

    local STARSHIP_CONFIG="$HOME/.config/starship.toml"
    local TEMPLATE_FILE="${SCRIPT_DIR}/templates/starship.toml"

    # Backup existing config
    if [ -f "$STARSHIP_CONFIG" ]; then
        echo -e "${CYAN}[BİLGİ]${NC} Mevcut Starship config yedekleniyor..."
        cp "$STARSHIP_CONFIG" "${STARSHIP_CONFIG}.backup.$(date +%Y%m%d_%H%M%S)"
    fi

    mkdir -p "$HOME/.config"

    # REFACTOR O-2: Load from template instead of 412-line heredoc
    if [ -f "$TEMPLATE_FILE" ]; then
        echo -e "${CYAN}[BİLGİ]${NC} Template'den yükleniyor: $TEMPLATE_FILE"
        cp "$TEMPLATE_FILE" "$STARSHIP_CONFIG"
    else
        # Fallback: Use embedded heredoc if template missing
        echo -e "${YELLOW}[UYARI]${NC} Template bulunamadı, embedded config kullanılıyor"
        cat > "$STARSHIP_CONFIG" << 'EOF'
# Starship Configuration - 1453 WSL Setup
# Theme: Catppuccin Mocha + Nerd Fonts

# Catppuccin Mocha Color Palette
palette = "catppuccin_mocha"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

# Format
format = """
[+----------------------------------->](bold green)
[|](bold green)$username$hostname$shlvl$directory$git_branch$git_status$git_commit$git_state
[|](bold green)$nodejs$bun$deno$python$golang$rust$php$java$ruby$lua
[|](bold green)$docker_context$kubernetes$terraform$cmake$conda
[+->](bold green)$character"""

# Right format
right_format = """$jobs $cmd_duration $time"""

# Character (Prompt symbol)
[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"

# Username
[username]
style_user = "bold yellow"
style_root = "bold red"
format = "[$user]($style) "
disabled = false
show_always = false

# Hostname
[hostname]
ssh_only = true
style = "bold green"
format = "[@$hostname]($style) "
disabled = false

# Shell Level
[shlvl]
disabled = false
symbol = "↕ "
style = "bold yellow"
threshold = 2
format = "[$symbol$shlvl]($style) "

# Jobs
[jobs]
symbol = "✦ "
style = "bold blue"
number_threshold = 1
symbol_threshold = 1
format = "[$symbol$number]($style) "

# Directory
[directory]
style = "bold blue"
read_only = " 󰌾"
truncation_length = 3
truncate_to_repo = true
format = "[$path]($style)[$read_only]($read_only_style) "

# Git Branch
[git_branch]
symbol = " "
style = "bold mauve"
format = "[$symbol$branch]($style) "

# Git Status
[git_status]
style = "bold red"
format = "([$all_status$ahead_behind]($style) )"
conflicted = "✖"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = "[+]"
untracked = "?${count}"
stashed = "$"
modified = "!${count}"
staged = "[++${count}](green)"
renamed = "»${count}"
deleted = "✘${count}"

# Git Commit
[git_commit]
commit_hash_length = 7
tag_symbol = "  "
style = "bold green"
format = '[\($hash$tag\)]($style) '

# Git State
[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
style = "bold yellow"
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"

# Time
[time]
disabled = false
time_format = "%R"
style = "bold yellow"
format = '[$time]($style) '

# Command Duration
[cmd_duration]
min_time = 500
style = "bold yellow"
format = "[took $duration]($style)"

# Programming Languages
[nodejs]
symbol = " "
style = "bold green"
format = "[$symbol($version )]($style)"

[bun]
symbol = "󰛢 "
style = "bold peach"
format = "[$symbol($version )]($style)"

[deno]
symbol = "🦕 "
style = "bold green"
format = "[$symbol($version )]($style)"

[python]
symbol = " "
style = "bold yellow"
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[golang]
symbol = " "
style = "bold cyan"
format = "[$symbol($version )]($style)"

[rust]
symbol = "󱘗 "
style = "bold red"
format = "[$symbol($version )]($style)"

[php]
symbol = " "
style = "bold mauve"
format = "[$symbol($version )]($style)"

[java]
symbol = " "
style = "bold red"
format = "[$symbol($version )]($style)"

[ruby]
symbol = " "
style = "bold red"
format = "[$symbol($version )]($style)"

[lua]
symbol = " "
style = "bold blue"
format = "[$symbol($version )]($style)"

[kotlin]
symbol = " "
style = "bold mauve"
format = "[$symbol($version )]($style)"

[rlang]
symbol = "R "
style = "bold blue"
format = "[$symbol($version )]($style)"

[perl]
symbol = " "
style = "bold blue"
format = "[$symbol($version )]($style)"

[zig]
symbol = " "
style = "bold yellow"
format = "[$symbol($version )]($style)"

[vlang]
symbol = " "
style = "bold blue"
format = "[$symbol($version )]($style)"

[crystal]
symbol = " "
style = "bold teal"
format = "[$symbol($version )]($style)"

# DevOps & Infrastructure Tools
[docker_context]
symbol = " "
style = "bold blue"
format = "[$symbol$context]($style) "

[container]
symbol = "⬢ "
style = "bold blue"
format = "[$symbol \\[$name\\]]($style) "

[kubernetes]
symbol = "☸ "
style = "bold blue"
format = '[$symbol$context( \($namespace\))]($style) '
disabled = false

[terraform]
symbol = "💠 "
style = "bold mauve"
format = "[$symbol$workspace]($style) "

[vagrant]
symbol = "⍱ "
style = "bold cyan"
format = "[$symbol($version )]($style)"

[aws]
symbol = "  "
style = "bold yellow"
format = '[$symbol($profile )(\($region\) )(\[$duration\] )]($style)'

[gcloud]
symbol = "󱇶 "
style = "bold blue"
format = '[$symbol$account(@$domain)(\($region\))]($style) '

[azure]
symbol = "󰠅 "
style = "bold blue"
format = "[$symbol($subscription)]($style) "

# Package Managers & Build Tools
[package]
symbol = "󰏗 "
style = "bold peach"
format = "[$symbol$version]($style) "

[cmake]
symbol = "△ "
style = "bold blue"
format = "[$symbol($version )]($style)"

[gradle]
symbol = " "
style = "bold cyan"
format = "[$symbol($version )]($style)"

# Less Common Languages & Tools
[buf]
symbol = " "
style = "bold blue"
format = "[$symbol($version )]($style)"

[c]
symbol = " "
style = "bold blue"
format = "[$symbol($version )]($style)"

[conda]
symbol = " "
style = "bold green"
format = "[$symbol$environment]($style) "

[dart]
symbol = " "
style = "bold blue"
format = "[$symbol($version )]($style)"

[elixir]
symbol = " "
style = "bold mauve"
format = '[$symbol($version \(OTP $otp_version\) )]($style)'

[elm]
symbol = " "
style = "bold cyan"
format = "[$symbol($version )]($style)"

[erlang]
symbol = " "
style = "bold red"
format = "[$symbol($version )]($style)"

[fennel]
symbol = " "
style = "bold green"
format = "[$symbol($version )]($style)"

[fossil_branch]
symbol = " "
style = "bold mauve"
format = "[$symbol$branch]($style) "

[haskell]
symbol = " "
style = "bold mauve"
format = "[$symbol($version )]($style)"

[haxe]
symbol = " "
style = "bold peach"
format = "[$symbol($version )]($style)"

[hg_branch]
symbol = " "
style = "bold mauve"
format = "[$symbol$branch]($style) "

[julia]
symbol = " "
style = "bold mauve"
format = "[$symbol($version )]($style)"

[memory_usage]
symbol = "󰍛 "
style = "bold yellow"
format = "$symbol[$ram( | $swap)]($style) "
disabled = true

[meson]
symbol = "⬢ "
style = "bold blue"
format = "[$symbol$project]($style) "

[nim]
symbol = "󰆥 "
style = "bold yellow"
format = "[$symbol($version )]($style)"

[nix_shell]
symbol = " "
style = "bold blue"
format = '[$symbol$state( \($name\))]($style) '

[ocaml]
symbol = " "
style = "bold yellow"
format = '[$symbol($version )(\($switch_indicator$switch_name\) )]($style)'

[purescript]
symbol = " "
style = "bold text"
format = "[$symbol($version )]($style)"

[raku]
symbol = " "
style = "bold blue"
format = "[$symbol($version-$vm_version )]($style)"

[red]
symbol = " "
style = "bold red"
format = "[$symbol($version )]($style)"

[scala]
symbol = " "
style = "bold red"
format = "[$symbol($version )]($style)"

[solidity]
symbol = " "
style = "bold blue"
format = "[$symbol($version )]($style)"

[swift]
symbol = " "
style = "bold peach"
format = "[$symbol($version )]($style)"

[typst]
symbol = " "
style = "bold peach"
format = "[$symbol($version )]($style)"

EOF
    fi

    echo -e "${GREEN}[BAŞARILI]${NC} Starship yapılandırıldı: $STARSHIP_CONFIG"
    echo -e "${CYAN}[BİLGİ]${NC} JetBrainsMono Nerd Font Mono ile kullanın"
    return 0
}

# Export functions
export -f setup_custom_shell
export -f setup_bash_aliases
export -f setup_custom_functions
export -f setup_bashrc_enhancements
export -f setup_starship_config
