#!/bin/bash
# Module: Shell Setup
# Description: Configure shell with custom aliases, functions, and settings
# Dependencies: common.sh

# Main shell setup function
setup_custom_shell() {
    echo -e "\n${BLUE}╔═══════════════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║          SHELL ORTAMI HAZIRLANIYOR            ║${NC}"
    echo -e "${BLUE}╚═══════════════════════════════════════════════╝${NC}"

    # Run setup functions with error checking
    if ! setup_bash_aliases; then
        track_failure "Shell Configuration" "Alias kurulumu başarısız"
        return 1
    fi

    if ! setup_custom_functions; then
        track_failure "Shell Configuration" "Fonksiyon kurulumu başarısız"
        return 1
    fi

    if ! setup_bashrc_enhancements; then
        track_failure "Shell Configuration" "Bashrc geliştirmeleri başarısız"
        return 1
    fi

    if ! setup_starship_config; then
        track_failure "Shell Configuration" "Starship config başarısız"
        return 1
    fi

    track_success "Shell Configuration" "(62 aliases, starship, enhancements)"
    echo -e "\n${GREEN}[BAŞARILI]${NC} Shell ortamı yapılandırması tamamlandı!"
    echo -e "${YELLOW}[BİLGİ]${NC} Değişikliklerin aktif olması için: ${GREEN}source ~/.bashrc${NC}"
    return 0
}

# Setup custom aliases
setup_bash_aliases() {
    echo -e "${YELLOW}[BİLGİ]${NC} Özel alias'lar yapılandırılıyor..."

    local ALIASES_FILE="$HOME/.bash_aliases"

    # Create backup if file exists
    if [ -f "$ALIASES_FILE" ]; then
        cp "$ALIASES_FILE" "${ALIASES_FILE}.backup.$(date +%Y%m%d_%H%M%S)"
        echo -e "${CYAN}[BİLGİ]${NC} Mevcut .bash_aliases yedeklendi."
    fi

    # Write aliases to file
    cat > "$ALIASES_FILE" << 'EOF'
# ============================================================================
# Custom Aliases - Auto-generated by 1453 WSL Setup
# ============================================================================

# Navigation aliases
alias ..='cd ..'
alias ...='cd ../..'
alias home='cd ~'
alias projects='cd ~/projects'
alias dl='cd ~/Downloads'

# Clear screen aliases
alias c='clear'
alias cl='clear'
alias cls='clear'

# Modern tool replacements (if installed)
alias cat='batcat'
alias grep='rg'
alias find='fdfind'
alias ls='eza --icons --group-directories-first'
alias ll='eza --icons --group-directories-first -l -g --git'
alias la='eza -a'
alias ld='lazydocker 2>/dev/null || docker ps -a'
alias lg='lazygit 2>/dev/null || git log --oneline --graph --decorate --all'

# Safe operations
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'

# System information
alias cpuinfo='lscpu'
alias meminfo='free -m -l -t'
alias disk='df -h'
alias ports='netstat -tulanp'
alias myip="curl -s http://whatismijnip.nl | cut -d ' ' -f 5"

# Git aliases
alias g='git'
alias ga='git add'
alias gaa='git add --all'
alias gb='git branch'
alias gc='git commit -m'
alias gca='git commit --amend'
alias gco='git checkout'
alias gl='git log --oneline --graph --decorate'
alias gp='git push'
alias gpf='git push --force-with-lease'
alias gpl='git pull'
alias gs='git status -s'
alias gst='git status'

# Docker aliases
alias dps='docker ps'
alias dpsa='docker ps -a'
alias di='docker images'
alias dex='docker exec -it'
alias dlog='docker logs -f'
alias dstop='docker stop $(docker ps -q)'
alias drm='docker rm $(docker ps -aq)'
alias dclean='docker system prune -af'

# NPM aliases
alias ni='npm install'
alias nid='npm install --save-dev'
alias nig='npm install -g'
alias nci='rm -rf node_modules package-lock.json && npm install'
alias ns='npm start'
alias nd='npm run dev'
alias nb='npm run build'
alias nt='npm test'

# Python aliases
alias py='python3'
alias pip='pip3'
alias venv='python3 -m venv'
alias activate='source venv/bin/activate'

# Process management
alias pg='ps aux | grep'

# Shell config editing
alias bashrc='nano ~/.bashrc'
alias aliases='nano ~/.bash_aliases'
alias reload='source ~/.bashrc'

# Zoxide (smart cd)
alias z='z'

EOF

    # Ensure .bashrc sources .bash_aliases
    if ! grep -q "\.bash_aliases" "$HOME/.bashrc" 2>/dev/null; then
        echo "" >> "$HOME/.bashrc"
        echo "# Source custom aliases" >> "$HOME/.bashrc"
        echo "[ -f ~/.bash_aliases ] && . ~/.bash_aliases" >> "$HOME/.bashrc"
    fi

    echo -e "${GREEN}[BAŞARILI]${NC} Alias'lar yapılandırıldı: $ALIASES_FILE"
    return 0
}

# Setup custom functions
setup_custom_functions() {
    echo -e "${YELLOW}[BİLGİ]${NC} Özel fonksiyonlar ekleniyor..."

    local BASHRC="$HOME/.bashrc"

    # Check if functions already exist
    if grep -q "===== START: Custom Functions - 1453 WSL Setup =====" "$BASHRC" 2>/dev/null; then
        echo -e "${CYAN}[BİLGİ]${NC} Özel fonksiyonlar zaten mevcut."
        return 0
    fi

    # Add custom functions to .bashrc
    cat >> "$BASHRC" << 'EOF'

# ===== START: Custom Functions - 1453 WSL Setup =====
# Create directory and cd into it
mcd() {
    mkdir -p "$1" && cd "$1" || exit
}

# Make file executable
make() {
    chmod +x "$1"
}
# ===== END: Custom Functions - 1453 WSL Setup =====

EOF

    echo -e "${GREEN}[BAŞARILI]${NC} Özel fonksiyonlar eklendi."
    return 0
}

# Setup enhanced bashrc configuration
setup_bashrc_enhancements() {
    echo -e "${YELLOW}[BİLGİ]${NC} Bash yapılandırması geliştiriliyor..."

    local BASHRC="$HOME/.bashrc"

    # Check if enhancements already exist
    if grep -q "===== START: Enhanced Bash Config - 1453 WSL Setup =====" "$BASHRC" 2>/dev/null; then
        echo -e "${CYAN}[BİLGİ]${NC} Bash geliştirmeleri zaten mevcut."
        return 0
    fi

    # Add enhanced configuration
    cat >> "$BASHRC" << 'EOF'

# ===== START: Enhanced Bash Config - 1453 WSL Setup =====

# History settings
export HISTCONTROL=ignoreboth:erasedups
export HISTSIZE=100000
export HISTFILESIZE=200000
export HISTTIMEFORMAT="%F %T "
export HISTIGNORE="ls:ll:la:pwd:exit:history:clear:cd"
shopt -s histappend

# Update history after each command
PROMPT_COMMAND="history -a; history -c; history -r; ${PROMPT_COMMAND}"

# Terminal settings
export TERM=xterm-256color

# Modern tool configurations
if command -v starship &>/dev/null; then
    eval "$(starship init bash)"
fi

if command -v zoxide &>/dev/null; then
    eval "$(zoxide init bash)"
fi

if command -v vivid &>/dev/null; then
    export LS_COLORS="$(vivid generate catppuccin-mocha)"
fi

# FZF configuration
if [ -f /usr/share/doc/fzf/examples/key-bindings.bash ]; then
    source /usr/share/doc/fzf/examples/key-bindings.bash
fi

if [ -f /usr/share/doc/fzf/examples/completion.bash ]; then
    source /usr/share/doc/fzf/examples/completion.bash
fi

# FZF default options (modern theme)
if command -v fzf &> /dev/null; then
    export FZF_DEFAULT_OPTS='--color=bg+:#313244,bg:#1e1e2e,spinner:#f5e0dc,hl:#f38ba8 --color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc --color=marker:#f5e0dc,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8 --border=rounded --height=80% --layout=reverse'
fi

# Add ~/.local/bin to PATH
export PATH="$HOME/.local/bin:$PATH"

# WSL specific settings
export BROWSER=wslview

# ===== END: Enhanced Bash Config - 1453 WSL Setup =====

EOF

    echo -e "${GREEN}[BAŞARILI]${NC} Bash yapılandırması geliştirildi."
    return 0
}

# Setup Starship configuration
setup_starship_config() {
    if ! command -v starship &> /dev/null; then
        echo -e "${CYAN}[BİLGİ]${NC} Starship kurulu değil, config atlanıyor."
        return 0
    fi

    echo -e "${YELLOW}[BİLGİ]${NC} Starship yapılandırması oluşturuluyor..."

    local STARSHIP_CONFIG="$HOME/.config/starship.toml"

    if [ -f "$STARSHIP_CONFIG" ]; then
        echo -e "${CYAN}[BİLGİ]${NC} Starship config zaten mevcut."
        return 0
    fi

    mkdir -p "$HOME/.config"

    # Create Starship configuration with Nerd Font icons
    cat > "$STARSHIP_CONFIG" << 'EOF'
# Starship Configuration - 1453 WSL Setup

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " 󰌾"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = "󰏗 "

[python]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

EOF

    echo -e "${GREEN}[BAŞARILI]${NC} Starship yapılandırıldı: $STARSHIP_CONFIG"
    return 0
}

# Export functions
export -f setup_custom_shell
export -f setup_bash_aliases
export -f setup_custom_functions
export -f setup_bashrc_enhancements
export -f setup_starship_config
